// Generated by CoffeeScript 1.10.0
(function() {
  riot.mount('todo', {
    items: [
      {
        title: 'Avoid excessive coffeine',
        done: true
      }, {
        title: 'Hidden item',
        hidden: true
      }, {
        title: 'Be less provocative'
      }, {
        title: 'Be nice to people'
      }
    ]
  });

}).call(this);
